apiVersion: v1
kind: Namespace
metadata:
  name: dev

---
apiVersion: v1
kind: Service
metadata:
  name: aden
  namespace: dev
  labels:
    app: aden
spec:
  selector:
    app: aden
  ports:
  - port: 80
    name: http
    targetPort: 80
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aden
  namespace: dev
spec:
  selector:
    matchLabels:
      app: aden
  strategy:
    type: RollingUpdate
  template: #Template for container
    metadata:
      labels:
        app: aden
    spec:
      containers:
      - name: aden
        image:  asia.gcr.io/$PROJECT_ID/dev/aden:$SHORT_SHA # ambil dari commit id terakhir
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: aden
        resources:
          requests:
            cpu: 50m

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: aden
  namespace: dev
spec:
  maxReplicas: 25
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aden
  targetCPUUtilizationPercentage: 100

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: balancer-dev
  namespace: dev
  annotations:
    kubernetes.io/ingress.global-static-ip-name: dev-ip # sesuaikan dengan nama ip publik
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/managed-certificates: aden
spec:
  rules:
    - host: app.kodecloud.tech
      http:
        paths:
        - path: /*
          pathType: ImplementationSpecific
          backend:
            service:
              name: aden
              port: 
                number: 80

---
apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: aden # sesuaikan dengan nama sertificatenya
  namespace: dev
spec:
  domains:
    - app.kodecloud.tech